name: gobabygo
services:
  proxy:
    image: "nginx:1.25"
    env_file: .env
    ports:
      - "8888:80"
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - webpack

  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: gobabygo
    ports:
      - ":8000"
    env_file: .env
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/opt/src

  worker:
    image: gobabygo
    env_file: .env
    command: "celery -A app.celery_conf worker -B --loglevel=info"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/opt/src

  webpack:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: gobabygo-frontend
    ports:
      - ":8080"
    command: "npm run-script start"
    volumes:
      - ./:/opt/src

  db:
    image: "postgres:15"
    env_file: .env
    ports:
      - ":5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:7"
    env_file: .env
    ports:
      - ":6379"

volumes:
  postgres-data:
