name: Test Bootstrapping

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run bootstrap script
      run: |
        ./bootstrap.sh myapp -d
        sleep 90

    - name: Check server response
      run: |
        docker ps -q | xargs -i% docker logs %
        RESPONSE_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8888/)
        if [ "$RESPONSE_CODE" -ne "200" ]
        then
          echo "The server did not return a 200 response code. Exiting with status 1."
          exit 1
        else
          echo "The server returned a 200 response code. Test success."
        fi